-- Root of the `NPuzzle` library; extend imports as you split the formalization.
import NPuzzle.Basic
import NPuzzle.Group.CycleThree
import NPuzzle.Rect.Basic
import NPuzzle.Rect.Config
import NPuzzle.FourFour
import NPuzzle.FourFour.Invariant
import NPuzzle.FourFour.Inversion
import NPuzzle.FourFour.TileListVertical
import NPuzzle.FourFour.BlankGrid
import NPuzzle.FourFour.BlankReach
import NPuzzle.FourFour.TileGlue
import NPuzzle.FourFour.TileSorted
import NPuzzle.FourFour.TileRank
import NPuzzle.FourFour.TileMacros
import NPuzzle.FourFour.TilePerm
import NPuzzle.FourFour.TileInverse
import NPuzzle.FourFour.TileConnectivity
import NPuzzle.FourFour.TileCycles
import NPuzzle.FourFour.Sufficiency
